-- Peran akses RBAC (permintaan pemilik 2026-10-07): peran dinamis berisi centang hak per aksi POLICY.
-- Aditif: tabel baru + kolom User.accessRoleId nullable (NULL = peran sistem jenis akunnya) + FK + indeks.
-- Empat peran sistem (data referensi produksi) dicentang PERSIS sesuai hak akses yang berlaku saat ini
-- (aksi POLICY yang mengizinkan jenis akunnya), sehingga deploy ini tidak mengubah perilaku siapa pun.

-- CreateTable
CREATE TABLE `AccessRole` (
    `id` VARCHAR(191) NOT NULL,
    `key` VARCHAR(64) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `description` VARCHAR(500) NULL,
    `baseRole` ENUM('SUPER_ADMIN', 'SCHOOL_ADMIN', 'SPONSOR', 'STUDENT') NOT NULL,
    `isSystem` BOOLEAN NOT NULL DEFAULT false,
    `permissions` JSON NOT NULL,
    `knownActions` JSON NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `AccessRole_key_key`(`key`),
    INDEX `AccessRole_baseRole_isSystem_idx`(`baseRole`, `isSystem`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AlterTable
ALTER TABLE `User` ADD COLUMN `accessRoleId` VARCHAR(191) NULL;

-- CreateIndex
CREATE INDEX `User_accessRoleId_idx` ON `User`(`accessRoleId`);

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_accessRoleId_fkey` FOREIGN KEY (`accessRoleId`) REFERENCES `AccessRole`(`id`) ON DELETE SET NULL ON UPDATE RESTRICT;

-- Peran sistem
INSERT INTO `AccessRole` (`id`, `key`, `name`, `description`, `baseRole`, `isSystem`, `permissions`, `knownActions`, `createdAt`, `updatedAt`) VALUES
  ('role_super_admin', 'super-admin', 'Super admin', 'Pengelola platform: semua sekolah, sponsor, iklan, dan pengguna.', 'SUPER_ADMIN', true, '["auth.self","auth.account","notification.self","file.read","region.read","platform.jobs.read","auth.totp","schools.manage","schools.profile.read","schools.settings.update","schools.theme.read","schools.theme.update","users.manage","users.impersonate","audit.platform.read","audit.login.read","audit.school.read","schoolAdmins.read","schoolAdmins.manage","roles.read","roles.manage","calendar.read","calendar.manage","calendar.national.read","calendar.national.manage","academics.read","academics.manage","students.read","students.manage","students.import","notification.push","attendance.monitor","attendance.correct","attendance.anomaly_review","attendance.reclose","attendance.test_mode","leave.review","reportCards.read","reportCards.manage","reportCards.publish","billing.read","billing.write","billing.verify","announcements.read","announcements.manage","dashboard.read","sponsor.admin","topup.review","ads.targeting.read","ads.analytics.read","ads.review"]', '["auth.self","auth.account","notification.self","file.read","region.read","platform.jobs.read","auth.totp","auth.email","schools.manage","schools.profile.read","schools.settings.update","schools.theme.read","schools.theme.update","users.manage","users.impersonate","audit.platform.read","audit.login.read","audit.school.read","schoolAdmins.read","schoolAdmins.manage","roles.read","roles.manage","calendar.read","calendar.manage","calendar.national.read","calendar.national.manage","calendar.student.read","academics.read","academics.manage","students.read","students.manage","students.import","students.profile.read","notification.preferences","notification.push","attendance.self","attendance.self.read","leave.self","leave.self.read","attendance.monitor","attendance.correct","attendance.anomaly_review","attendance.reclose","attendance.test_mode","leave.review","reportCards.read","reportCards.manage","reportCards.publish","reportCards.self.read","billing.read","billing.write","billing.verify","billing.self.read","billing.self.pay","announcements.read","announcements.manage","dashboard.read","sponsor.self.read","sponsor.self.write","sponsor.topup","sponsor.admin","topup.review","ads.own.read","ads.own.write","ads.own.submit","ads.targeting.read","ads.analytics.read","ads.review","ads.serve","ads.event"]', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('role_admin_sekolah', 'admin-sekolah', 'Admin sekolah', 'Admin & guru sekolah: siswa, absensi, akademik, rapor, SPP, pengumuman.', 'SCHOOL_ADMIN', true, '["auth.self","auth.account","notification.self","file.read","region.read","auth.email","schools.profile.read","schools.settings.update","schools.theme.read","schools.theme.update","audit.school.read","schoolAdmins.read","schoolAdmins.manage","roles.read","calendar.read","calendar.manage","academics.read","academics.manage","students.read","students.manage","students.import","notification.preferences","notification.push","attendance.monitor","attendance.correct","attendance.anomaly_review","leave.review","reportCards.read","reportCards.manage","reportCards.publish","billing.read","billing.write","billing.verify","announcements.read","announcements.manage","dashboard.read"]', '["auth.self","auth.account","notification.self","file.read","region.read","platform.jobs.read","auth.totp","auth.email","schools.manage","schools.profile.read","schools.settings.update","schools.theme.read","schools.theme.update","users.manage","users.impersonate","audit.platform.read","audit.login.read","audit.school.read","schoolAdmins.read","schoolAdmins.manage","roles.read","roles.manage","calendar.read","calendar.manage","calendar.national.read","calendar.national.manage","calendar.student.read","academics.read","academics.manage","students.read","students.manage","students.import","students.profile.read","notification.preferences","notification.push","attendance.self","attendance.self.read","leave.self","leave.self.read","attendance.monitor","attendance.correct","attendance.anomaly_review","attendance.reclose","attendance.test_mode","leave.review","reportCards.read","reportCards.manage","reportCards.publish","reportCards.self.read","billing.read","billing.write","billing.verify","billing.self.read","billing.self.pay","announcements.read","announcements.manage","dashboard.read","sponsor.self.read","sponsor.self.write","sponsor.topup","sponsor.admin","topup.review","ads.own.read","ads.own.write","ads.own.submit","ads.targeting.read","ads.analytics.read","ads.review","ads.serve","ads.event"]', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('role_sponsor', 'sponsor', 'Sponsor', 'Mitra pengiklan: profil, saldo, dan kampanye iklan.', 'SPONSOR', true, '["auth.self","auth.account","notification.self","file.read","region.read","notification.push","sponsor.self.read","sponsor.self.write","sponsor.topup","ads.own.read","ads.own.write","ads.own.submit","ads.targeting.read","ads.analytics.read"]', '["auth.self","auth.account","notification.self","file.read","region.read","platform.jobs.read","auth.totp","auth.email","schools.manage","schools.profile.read","schools.settings.update","schools.theme.read","schools.theme.update","users.manage","users.impersonate","audit.platform.read","audit.login.read","audit.school.read","schoolAdmins.read","schoolAdmins.manage","roles.read","roles.manage","calendar.read","calendar.manage","calendar.national.read","calendar.national.manage","calendar.student.read","academics.read","academics.manage","students.read","students.manage","students.import","students.profile.read","notification.preferences","notification.push","attendance.self","attendance.self.read","leave.self","leave.self.read","attendance.monitor","attendance.correct","attendance.anomaly_review","attendance.reclose","attendance.test_mode","leave.review","reportCards.read","reportCards.manage","reportCards.publish","reportCards.self.read","billing.read","billing.write","billing.verify","billing.self.read","billing.self.pay","announcements.read","announcements.manage","dashboard.read","sponsor.self.read","sponsor.self.write","sponsor.topup","sponsor.admin","topup.review","ads.own.read","ads.own.write","ads.own.submit","ads.targeting.read","ads.analytics.read","ads.review","ads.serve","ads.event"]', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('role_siswa', 'siswa', 'Siswa', 'Siswa: absen masuk & pulang, izin, rapor, tagihan, kalender.', 'STUDENT', true, '["auth.self","auth.account","notification.self","file.read","calendar.student.read","students.profile.read","notification.push","attendance.self","attendance.self.read","leave.self","leave.self.read","reportCards.self.read","billing.self.read","billing.self.pay","ads.serve","ads.event"]', '["auth.self","auth.account","notification.self","file.read","region.read","platform.jobs.read","auth.totp","auth.email","schools.manage","schools.profile.read","schools.settings.update","schools.theme.read","schools.theme.update","users.manage","users.impersonate","audit.platform.read","audit.login.read","audit.school.read","schoolAdmins.read","schoolAdmins.manage","roles.read","roles.manage","calendar.read","calendar.manage","calendar.national.read","calendar.national.manage","calendar.student.read","academics.read","academics.manage","students.read","students.manage","students.import","students.profile.read","notification.preferences","notification.push","attendance.self","attendance.self.read","leave.self","leave.self.read","attendance.monitor","attendance.correct","attendance.anomaly_review","attendance.reclose","attendance.test_mode","leave.review","reportCards.read","reportCards.manage","reportCards.publish","reportCards.self.read","billing.read","billing.write","billing.verify","billing.self.read","billing.self.pay","announcements.read","announcements.manage","dashboard.read","sponsor.self.read","sponsor.self.write","sponsor.topup","sponsor.admin","topup.review","ads.own.read","ads.own.write","ads.own.submit","ads.targeting.read","ads.analytics.read","ads.review","ads.serve","ads.event"]', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));
