/**
 * Status HTTP untuk setiap kode AppError yang dilempar di src/lib (hasil grep badRequest/unauthorized/
 * forbidden/notFound/conflict/gone/unprocessable/tooManyRequests/serviceUnavailable/`new AppError`,
 * plus kode RuleViolation yang dilempar lewat assertNoViolation). Dipakai dokumentasi OpenAPI untuk
 * mengelompokkan `contract.errors` per status; status runtime tetap ditentukan AppError yang dilempar.
 *
 * Kode yang dilempar dengan status berbeda di tempat berbeda dipetakan ke status yang paling sering
 * (daftar lengkap di MIXED_STATUS_CODES):
 * - ACCOUNT_INACTIVE -> 401 (get-auth, refresh-service); 403 hanya saat login (login-service).
 *
 * Kode baru WAJIB ditambahkan di sini (dicek error-status.test.ts). Kode tak dikenal -> 422.
 */
export const DEFAULT_ERROR_STATUS = 422;

export const ERROR_STATUS: Readonly<Record<string, number>> = Object.freeze({
  // 400 — permintaan tidak valid / endpoint salah.
  VALIDATION_FAILED: 400, INVALID_JSON: 400, INVALID_MULTIPART: 400, INVALID_CURSOR: 400, INVALID_STORAGE_KEY: 400,
  CANNOT_TARGET_SELF: 400, CURRENT_PASSWORD_INVALID: 400, DEVICE_ID_REQUIRED: 400,
  SCHOOL_ID_NOT_ALLOWED: 400, SCHOOL_ID_REQUIRED: 400, SPONSOR_ID_REQUIRED: 400,
  USE_CHANGE_PASSWORD: 400, USE_DEDICATED_ENDPOINT: 400, USE_STUDENT_ENDPOINT: 400, USE_STUDENT_STATUS: 400,
  GRADE_ROWS_INVALID: 400,
  // 401 — tidak terautentikasi.
  UNAUTHENTICATED: 401, TOKEN_EXPIRED: 401, SESSION_INVALID: 401, INVALID_CREDENTIALS: 401, ACCOUNT_INACTIVE: 401,
  // 403 — akses ditolak.
  FORBIDDEN: 403, SCOPE_MISMATCH: 403, PASSWORD_CHANGE_REQUIRED: 403, TEMP_PASSWORD_EXPIRED: 403, STUDENT_NOT_ACTIVE: 403,
  CHECKIN_MOBILE_ONLY: 403,
  // 404 — tidak ditemukan (termasuk milik sekolah lain).
  NOT_FOUND: 404, SCHOOL_NOT_FOUND: 404, CLASS_NOT_FOUND: 404,
  // 409 — konflik status/duplikat/bentrokan bersamaan.
  DUPLICATE: 409, CONFLICT_RETRY: 409, STATE_CONFLICT: 409, INVALID_STATUS_TRANSITION: 409, REFRESH_RACE: 409,
  PASSWORD_CHANGED_CONCURRENTLY: 409,
  ACADEMIC_YEAR_IN_USE: 409, ACADEMIC_YEAR_NAME_TAKEN: 409, ACADEMIC_YEAR_OVERLAP: 409,
  TERM_ACTIVE: 409, TERM_HAS_ATTENDANCE: 409, TERM_IN_USE: 409, TERM_SEMESTER_TAKEN: 409,
  CLASS_HAS_STUDENTS: 409, CLASS_IN_USE: 409, CLASS_NAME_TAKEN: 409,
  SUBJECT_CODE_LOCKED: 409, SUBJECT_CODE_TAKEN: 409, SUBJECT_IN_USE: 409, SUBJECT_MAPPED: 409,
  HOLIDAY_DUPLICATE: 409, IMPORT_CONFLICT: 409, EMAIL_TAKEN: 409, NPSN_TAKEN: 409, LAST_SUPER_ADMIN: 409,
  SCHOOL_ALREADY_ACTIVE: 409, SCHOOL_ALREADY_INACTIVE: 409, SCHOOL_INACTIVE: 409,
  USER_ALREADY_ACTIVE: 409, USER_ALREADY_INACTIVE: 409,
  NISN_ACTIVE_ELSEWHERE: 409, NISN_ALREADY_IN_SCHOOL: 409, NISN_LOCKED: 409, NIS_ALREADY_IN_SCHOOL: 409,
  STUDENT_IN_USE: 409, STUDENT_NOT_DRAFT: 409, STUDENT_STATE_CHANGED: 409, NISN_HELD_BY_GRADUATE: 409,
  ATTENDANCE_ALREADY_RECORDED: 409, LEAVE_OVERLAP: 409, LEAVE_NOT_PENDING: 409, LEAVE_ALREADY_REVIEWED: 409,
  LEAVE_STUDENT_INACTIVE: 409,
  REPORT_CARD_PUBLISHED: 409, REPORT_CARD_EXISTS: 409, REPORT_CARD_NOT_PUBLISHED: 409,
  INVOICE_EXISTS: 409, INVOICE_VOID: 409, INVOICE_NOT_VOID: 409, INVOICE_ALREADY_PAID: 409, INVOICE_HAS_PAYMENTS: 409,
  INVOICE_NOT_PAYABLE: 409, SUBMISSION_PENDING: 409, SUBMISSION_NOT_PENDING: 409, SUBMISSION_ALREADY_REVIEWED: 409,
  PAYMENT_ALREADY_VOIDED: 409, ANNOUNCEMENT_NOT_DRAFT: 409,
  // 410 / 411 / 413 / 415 — berkas & transport body.
  FILE_PURGED: 410,
  LENGTH_REQUIRED: 411,
  PAYLOAD_TOO_LARGE: 413,
  UNSUPPORTED_MEDIA_TYPE: 415, HEIC_NOT_SUPPORTED: 415,
  // 422 — pelanggaran aturan bisnis (termasuk RuleViolation lewat assertNoViolation).
  ACTIVATION_INCOMPLETE: 422, CLASS_INACTIVE: 422, SUBJECT_INACTIVE: 422, CITY_NOT_IN_PROVINCE: 422,
  SCHOOL_CONFIG_INVALID: 422, BANNER_INVALID: 422, PASSWORD_POLICY: 422, PASSWORD_REUSED: 422,
  PUSH_TOKEN_INVALID: 422, PUSH_TOKEN_WEB_SESSION: 422, HOLIDAY_BACKDATE_LIMIT: 422, HOLIDAY_TOO_LONG: 422,
  IMAGE_TOO_LARGE: 422, IMAGE_TOO_SMALL: 422, IMAGE_UNREADABLE: 422,
  IMPORT_EMPTY: 422, IMPORT_FILE_INVALID: 422, IMPORT_HEADERS_DUPLICATE: 422, IMPORT_HEADERS_MISSING: 422,
  IMPORT_INVALID: 422, IMPORT_TOO_MANY_ROWS: 422, INVALID_DATE_RANGE: 422,
  ACADEMIC_YEAR_EXCLUDES_TERMS: 422, ACADEMIC_YEAR_NAME_INVALID: 422, ACADEMIC_YEAR_NAME_MISMATCH: 422,
  ACADEMIC_YEAR_TOO_LONG: 422, TERM_ORDER_INVALID: 422, TERM_OUTSIDE_YEAR: 422, TERM_TOO_LONG: 422,
  NOT_SCHOOL_DAY: 422, CHECKIN_NOT_OPEN: 422, CHECKIN_CLOSED: 422, INVALID_LOCATION: 422, MOCK_LOCATION: 422,
  LOCATION_STALE: 422, GPS_ACCURACY_TOO_LOW: 422, OUTSIDE_GEOFENCE: 422, MONTH_OUT_OF_RANGE: 422,
  LEAVE_TOO_LONG: 422, LEAVE_BACKDATE_LIMIT: 422, LEAVE_ADVANCE_LIMIT: 422, NO_SCHOOL_DAYS_IN_RANGE: 422,
  ATTACHMENT_REQUIRED: 422, FUTURE_DATE: 422, CORRECTION_WINDOW_EXPIRED: 422, DAY_NOT_CLOSED: 422, DATE_BEFORE_SCHOOL_START: 422,
  SUBJECT_NOT_IN_CLASS: 422, CLASS_TERM_MISMATCH: 422, CLASS_HAS_NO_SUBJECTS: 422, REPORT_CARD_INCOMPLETE: 422,
  STUDENT_NOT_ELIGIBLE: 422,
  PERIOD_OUT_OF_RANGE: 422, DUE_DATE_OUT_OF_RANGE: 422, STUDENT_NOT_BILLABLE: 422, AMOUNT_EXCEEDS_REMAINING: 422,
  AMOUNT_TOO_SMALL: 422, PARTIAL_NOT_ALLOWED: 422, APPROVED_AMOUNT_INVALID: 422, NOTE_REQUIRED: 422,
  TRANSFER_DATE_OUT_OF_RANGE: 422, PAID_DATE_OUT_OF_RANGE: 422, BULK_TOO_LARGE: 422, BULK_OVERRIDE_OUT_OF_SCOPE: 422,
  INVALID_TARGETS: 422, NO_RECIPIENTS: 422, ANNOUNCEMENT_NOT_EDITABLE: 422,
  // 429 / 500 / 503.
  RATE_LIMITED: 429, NISN_RELEASE_LIMIT: 429, LEAVE_DAILY_LIMIT: 429, TOO_MANY_SUBMISSIONS: 429,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
});

/** Kode yang dilempar dengan lebih dari satu status (ERROR_STATUS memuat yang paling sering). */
export const MIXED_STATUS_CODES: Readonly<Record<string, readonly number[]>> = Object.freeze({
  ACCOUNT_INACTIVE: [401, 403],
});

/** Status HTTP terdokumentasi untuk sebuah kode error; kode tak dikenal -> 422. */
export function statusForCode(code: string): number {
  return Object.hasOwn(ERROR_STATUS, code) ? (ERROR_STATUS[code] ?? DEFAULT_ERROR_STATUS) : DEFAULT_ERROR_STATUS;
}
